# Generated by Django 4.2.20 on 2025-05-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cntrydetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='cntrydetails.subregion'),
        ),
    ]
