# Generated by Django 4.2.20 on 2025-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntrydetails', '0002_alter_country_subregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='ccn3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
